# Generated by Django 5.0.6 on 2025-07-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicio_anfitrion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='num_persona',
            field=models.IntegerField(default=1, help_text='Número de personas que pueden participar en esta actividad'),
        ),
    ]
