# Generated by Django 5.0.6 on 2025-07-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicio_num_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
    ]
