# Generated by Django 5.0.6 on 2025-07-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_servicio_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='detallecarrito',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='DetalleCarrito',
        ),
    ]
