# Generated by Django 5.0.6 on 2025-07-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_detallecarrito_carrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='num_persona',
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='num_persona',
            field=models.IntegerField(default=1, help_text='Número de personas que pueden participar en esta actividad'),
        ),
    ]
